version: "3.9"

services:
  argus_bot:
    build:
      context: .
      dockerfile: docker/bot.Dockerfile
    network_mode: host            # let DDS multicast hit the host stack
    environment:
      - ROS_DOMAIN_ID=42          # pick any integer; same for all nodes
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    # Optional GUI: forward X11
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    environment:
      - DISPLAY=${DISPLAY}

  argus_command_bridge:
    build:
      context: .
      dockerfile: docker/bridge.Dockerfile
    network_mode: host
    depends_on:
      - argus_bot
    environment:
      - ROS_DOMAIN_ID=42
